version: "3.4"
services:
  http:
    image: nginx
    volumes:
      - ${BACKEND_DIR}:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ${FRONTEND_DIR}:/var/www/frontend
    ports:
      - 8081:81
      - 8080:80
  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ../alteza4-test:/var/www/html
    environment:
      EXTERNAL_DATABASE_URL: "mysql://root:${MYSQL_ROOT_PASSWORD}@db/alteza"
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
  build:
    build:
      context: .
      dockerfile: heroku.Dockerfile
    volumes:
      - ../alteza-website-4.0:/app
    environment:
      - REACT_APP_API_ENDPOINT: "http://localhost:8081/wp-json/"
      - REACT_APP_GOOGLE_MAPS_API_KEY: "api_key"

volumes:
  db:
